language: erlang

otp_release:
  - 21.0
  - 20.3
  - 19.3
  - 18.3

install: make clean

script:
- wget -c https://github.com/erlang/rebar3/releases/download/3.6.1/rebar3
- chmod +x rebar3
- make all
